name: Node.js (with nave) CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: ./venv.sh yarn
    - name: Build for production
      run: ./venv.sh yarn build
    - name: Unit tests
      env:
        CI: true
      run: ./venv.sh yarn test
    - name: End-to-End (e2e) tests
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: ./venv.sh e2etest-all

