name: Node.js (with nave) CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: ./venv.sh yarn
    - run: ./venv.sh yarn build
    - run: ./venv.sh yarn test
      env:
        CI: true
