name: Node.js (with nave) CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: ./venv.sh yarn
    - name: Build for production
      run: ./venv.sh yarn build
    - name: Tests
      run: ./venv.sh yarn test
      env:
        CI: true

